### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import os

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [5]:
players = {
    'Total Number of Players': [purchase_data['SN'].count()]
}

totalplayers_count = pd.DataFrame(players)
totalplayers_count

   Total Number of Players
0                      780

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [6]:
total_unique_items = purchase_data['Item Name'].count()
total_avg_price = purchase_data['Price'].mean()
total_purchases = purchase_data['Price'].count()
total_revenue = purchase_data['Price'].sum()

purchase_analysis = {
    'Number of Unique Items': [purchase_data['Item Name'].count()],
    'Average Price': [purchase_data['Price'].mean()],
    'Number of Purchases': [purchase_data['Price'].count()],
    'Total Revenue': [purchase_data['Price'].sum()]
}

purchase_analysis = pd.DataFrame(purchase_analysis)
purchase_analysis

   Number of Unique Items  Average Price  Number of Purchases  Total Revenue
0                     780       3.050987                  780        2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [7]:
# GENDER DEMOGRAPHICS

# Gender classification needed
players_by_gender = purchase_data['Gender'].value_counts()
players_by_gender = pd.DataFrame(players_by_gender)

# Calculate percentage of players by gender
percentage_of_players = (purchase_data['Gender'].value_counts() / (purchase_data['Gender'].count())) * 100

# Add 'Percentage of Players' to table
players_by_gender['Percentage of Players'] = percentage_of_players
gender_demographics = pd.DataFrame(players_by_gender)
gender_demographics

# Renaming 'Gender' to 'Total Count'
new_gender_demographics = gender_demographics.rename(columns={'Gender': 'Total Count',})
new_gender_demographics

                       Total Count  Percentage of Players
Male                           652              83.589744
Female                         113              14.487179
Other / Non-Disclosed           15               1.923077


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [8]:
# Calculate purchase count by gender
all_gender_df =purchase_data.groupby('Gender')

player_count = all_gender_df['SN'].count()
player_count_df = pd.DataFrame(player_count)
player_count_df

                        SN
Gender
Female                 113
Male                   652
Other / Non-Disclosed   15

In [9]:
# Calculate average purchase price by gender
avg_price = all_gender_df['Price'].mean()
avg_price_df = pd.DataFrame(avg_price)
avg_price_df

                          Price
Gender
Female                 3.203009
Male                   3.017853
Other / Non-Disclosed  3.346000

In [10]:
# Calculate total purchase price by gender
total_gender_purchase = all_gender_df['Price'].sum()
total_gender_purchase_df = pd.DataFrame(total_gender_purchase )
total_gender_purchase_df

                         Price
Gender
Female                  361.94
Male                   1967.64
Other / Non-Disclosed    50.19

In [11]:
# Calculate Purchase/Gender totals (total Purchase per category / total count per category)
Purchase_per_Gender_total= total_gender_purchase/player_count
Purchase_per_Gender_total_df = pd.DataFrame(Purchase_per_Gender_total )
Purchase_per_Gender_total_df

                              0
Gender
Female                 3.203009
Male                   3.017853
Other / Non-Disclosed  3.346000

In [12]:
#Add 'Average Purchase Price' to table
player_count_df['Average Purchase Price'] = avg_price
gender_purchase_df = pd.DataFrame(player_count_df)
gender_purchase_df

                        SN  Average Purchase Price
Gender
Female                 113                3.203009
Male                   652                3.017853
Other / Non-Disclosed   15                3.346000

In [13]:
# Rename 'SN' column to 'Purchase Count'
new_gender_purchase_df = gender_purchase_df.rename(columns={'SN': 'Purchase Count',})
new_gender_purchase_df

                       Purchase Count  Average Purchase Price
Gender
Female                            113                3.203009
Male                              652                3.017853
Other / Non-Disclosed              15                3.346000

In [14]:
# Add 'Total Purchase Price ' to table
new_gender_purchase_df['Total Purchase Price'] = total_gender_purchase
new_gender_purchase_df

,Purchase Count,Average Purchase Price,Total Purchase Price
Gender,,,
Female,113,3.203009,361.94
Male,652,3.017853,1967.64
Other / Non-Disclosed,15,3.346000,50.19

In [15]:
# Add 'Total Purchase Price' to table
new_gender_purchase_df['Purchase per Gender total'] = Purchase_per_Gender_total
new_gender_purchase_df

,Purchase Count,Average Purchase Price,Total Purchase Price,Purchase per Gender total
Gender,,,,
Female,113,3.203009,361.94,3.203009
Male,652,3.017853,1967.64,3.017853
Other / Non-Disclosed,15,3.346000,50.19,3.346000

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [16]:
# Create bins for different ranges of age groups
bins = [0, 10, 15, 20, 25, 30, 35, 40, 100]
group_names = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']

In [17]:
# Place total number of people per age group in their respective bins
purchase_data['Total Count'] = pd.cut(purchase_data['Age'],
                                     bins, labels=group_names)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Total Count
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,15-19
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,35-39
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,15-19
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,30-34
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,30-34
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,15-19
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,25-29
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,15-19
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,35-39
24,24,Siala43,30,Male,141,Persuasion,3.19,25-29
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,15-19
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,20-24
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,10-14
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,15-19
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [18]:
age_groups = purchase_data.groupby('Total Count')
age_groups_df = age_groups.count()
age_groups_df

             Purchase ID   SN  Age  Gender  Item ID  Item Name  Price
Total Count
<10                   32   32   32      32       32         32     32
10-14                 54   54   54      54       54         54     54
15-19                200  200  200     200      200        200    200
20-24                325  325  325     325      325        325    325
25-29                 77   77   77      77       77         77     77
30-34                 52   52   52      52       52         52     52
35-39                 33   33   33      33       33         33     33
40+                    7    7    7       7        7          7      7

In [19]:
organized_age_df = age_groups_df[['Age']]
organized_age_df

             Age
Total Count
<10           32
10-14         54
15-19        200
20-24        325
25-29         77
30-34         52
35-39         33
40+            7

In [21]:
percent_age_group = (organized_age_df / purchase_data['Gender'].count()) * 100
organized_age_df['Percent of players'] = percent_age_group
organized_age_df

C:\Users\jense\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

             Age  Percent of players
Total Count
<10           32            4.102564
10-14         54            6.923077
15-19        200           25.641026
20-24        325           41.666667
25-29         77            9.871795
30-34         52            6.666667
35-39         33            4.230769
40+            7            0.897436

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [22]:
bins2 = [10, 15, 20, 25, 30, 35, 40, 100]
group_names = ['10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40+']
purchase_data['Total Count'] = pd.cut(purchase_data['Age'],
                                     bins2, labels=group_names)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Total Count
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,15-19
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,35-39
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,15-19
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,30-34
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,30-34
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,15-19
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,25-29
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,15-19
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,35-39
24,24,Siala43,30,Male,141,Persuasion,3.19,25-29
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,NaN
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,15-19
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,20-24
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,NaN
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,10-14
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,15-19
778,778,Sisur91,7,Male,101,Final Critic,4.19,NaN
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [23]:
age_groups = purchase_data.groupby('Total Count')
age_groups_df = age_groups.count()
age_groups_df

             Purchase ID   SN  Age  Gender  Item ID  Item Name  Price
Total Count
10-14                 54   54   54      54       54         54     54
15-19                200  200  200     200      200        200    200
20-24                325  325  325     325      325        325    325
25-29                 77   77   77      77       77         77     77
30-34                 52   52   52      52       52         52     52
35-39                 33   33   33      33       33         33     33
40+                    7    7    7       7        7          7      7

In [25]:
age_groups_df =purchase_data.groupby('Total Count')

In [31]:
new_age = age_groups_df['Purchase ID'].count()
new_age_df = pd.DataFrame(new_age)
new_age_df

             Purchase ID
Total Count
10-14                 54
15-19                200
20-24                325
25-29                 77
30-34                 52
35-39                 33
40+                    7

In [32]:
new_df =new_age_df.rename(columns={'Purchase ID': 'Purchase Count',})
new_df

             Purchase Count
Total Count
10-14                    54
15-19                   200
20-24                   325
25-29                    77
30-34                    52
35-39                    33
40+                       7

In [33]:
avg_price = age_groups_df['Price'].mean()
avg_price_df = pd.DataFrame(avg_price)
avg_price_df

                Price
Total Count
10-14        2.900000
15-19        3.107800
20-24        3.020431
25-29        2.875584
30-34        2.994423
35-39        3.404545
40+          3.075714

In [34]:
new_df['Average Purchase Price'] = avg_price
new_age_df = pd.DataFrame(new_df)
new_age_df

             Purchase Count  Average Purchase Price
Total Count
10-14                    54                2.900000
15-19                   200                3.107800
20-24                   325                3.020431
25-29                    77                2.875584
30-34                    52                2.994423
35-39                    33                3.404545
40+                       7                3.075714

In [35]:
total_purchase_value = age_groups_df['Price'].sum()
total_purchase_value_df = pd.DataFrame(total_purchase_value)
total_purchase_value_df

              Price
Total Count
10-14        156.60
15-19        621.56
20-24        981.64
25-29        221.42
30-34        155.71
35-39        112.35
40+           21.53

In [36]:
new_df['Total Purchase Value'] = total_purchase_value
new_age_df = pd.DataFrame(new_df)
new_age_df

             Purchase Count  Average Purchase Price  Total Purchase Value
Total Count
10-14                    54                2.900000                156.60
15-19                   200                3.107800                621.56
20-24                   325                3.020431                981.64
25-29                    77                2.875584                221.42
30-34                    52                2.994423                155.71
35-39                    33                3.404545                112.35
40+                       7                3.075714                 21.53

In [47]:
total_item_df=purchase_data.groupby('Total Count')
total_item_df
total_purchase_id=total_item_df['Item ID'].count()
total_purchase_id

Avg_Total_Purchase_per_Person= (total_purchase_value/total_purchase_id)
Avg_Total_Purchase_per_Person_df = pd.DataFrame(Avg_Total_Purchase_per_Person )
Avg_Total_Purchase_per_Person_df

                    0
Total Count
10-14        2.900000
15-19        3.107800
20-24        3.020431
25-29        2.875584
30-34        2.994423
35-39        3.404545
40+          3.075714

In [66]:
new_df['Avg Total Purchase per Person'] = Avg_Total_Purchase_per_Person
new_age_df = pd.DataFrame(new_df)
new_age_df

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Total Count,,,,
10-14,54,2.900000,156.60,2.900000
15-19,200,3.107800,621.56,3.107800
20-24,325,3.020431,981.64,3.020431
25-29,77,2.875584,221.42,2.875584
30-34,52,2.994423,155.71,2.994423
35-39,33,3.404545,112.35,3.404545
40+,7,3.075714,21.53,3.075714

## Purchasing Analysis (Age)

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [74]:
top_spenders_df = purchase_data['Item ID'].groupby(purchase_data['SN']).count()
top_spenders_df

SN
Adairialis76       1
Adastirin33        1
Aeda94             1
Aela59             1
Aelaria33          1
Aelastirin39       2
Aelidru27          1
Aelin32            3
Aelly27            2
Aellynun67         1
Aellyria80         1
Aelollo59          2
Aenarap34          1
Aeral43            1
Aeral68            1
Aeral97            1
Aeralria27         1
Aeralstical35      1
Aeri84             1
Aerillorin70       1
Aerithllora36      2
Aerithnucal56      1
Aerithnuphos61     1
Aerithriaphos45    1
Aerithriaphos46    1
Aesri53            1
Aesty53            2
Aestysu37          2
Aesur96            1
Aesurstilis64      1
                  ..
Undosia27          1
Undosian34         2
Undotesta33        1
Wailin72           1
Yadacal26          2
Yadaisuir65        1
Yadam35            1
Yadanu52           1
Yadaphos40         2
Yalae81            2
Yalaeria91         1
Yaliru88           1
Yalo85             1
Yalostiphos68      1
Yana46             1
Yarithllodeu72     1
Yarithrgue83       1
Yarithrin84        1
Yarithsurgue62     1
Yarolwen77         1
Yasrisu92          1
Yastyriaphos75     1
Yasur35            1
Yasur85            1
Yathecal72         1
Yathecal82         3
Yathedeu43         2
Yoishirrala98      1
Zhisrisu83         2
Zontibe81          3
Name: Item ID, Length: 576, dtype: int64

In [75]:
# Creating the initial column in the Dataframe
top_spenders_df = pd.DataFrame(data=top_spenders_df)
top_spenders_df.columns = ['Purchase Count']
top_spenders_df

                 Purchase Count
SN
Adairialis76                  1
Adastirin33                   1
Aeda94                        1
Aela59                        1
Aelaria33                     1
Aelastirin39                  2
Aelidru27                     1
Aelin32                       3
Aelly27                       2
Aellynun67                    1
Aellyria80                    1
Aelollo59                     2
Aenarap34                     1
Aeral43                       1
Aeral68                       1
Aeral97                       1
Aeralria27                    1
Aeralstical35                 1
Aeri84                        1
Aerillorin70                  1
Aerithllora36                 2
Aerithnucal56                 1
Aerithnuphos61                1
Aerithriaphos45               1
Aerithriaphos46               1
Aesri53                       1
Aesty53                       2
Aestysu37                     2
Aesur96                       1
Aesurstilis64                 1
...                         ...
Undosia27                     1
Undosian34                    2
Undotesta33                   1
Wailin72                      1
Yadacal26                     2
Yadaisuir65                   1
Yadam35                       1
Yadanu52                      1
Yadaphos40                    2
Yalae81                       2
Yalaeria91                    1
Yaliru88                      1
Yalo85                        1
Yalostiphos68                 1
Yana46                        1
Yarithllodeu72                1
Yarithrgue83                  1
Yarithrin84                   1
Yarithsurgue62                1
Yarolwen77                    1
Yasrisu92                     1
Yastyriaphos75                1
Yasur35                       1
Yasur85                       1
Yathecal72                    1
Yathecal82                    3
Yathedeu43                    2
Yoishirrala98                 1
Zhisrisu83                    2
Zontibe81                     3

[576 rows x 1 columns]

In [77]:
# Calculating the column values
top_spenders_df['Average Purchase Price'] = round(purchase_data['Price'].groupby(purchase_data['SN']).mean(),2)
top_spenders_df['Total Purchase Value'] = purchase_data['Price'].groupby(purchase_data['SN']).sum()
top_spenders_df

                 Purchase Count  Average Purchase Price  Total Purchase Value
SN
Adairialis76                  1                    2.28                  2.28
Adastirin33                   1                    4.48                  4.48
Aeda94                        1                    4.91                  4.91
Aela59                        1                    4.32                  4.32
Aelaria33                     1                    1.79                  1.79
Aelastirin39                  2                    3.64                  7.29
Aelidru27                     1                    1.09                  1.09
Aelin32                       3                    2.99                  8.98
Aelly27                       2                    3.39                  6.79
Aellynun67                    1                    3.74                  3.74
Aellyria80                    1                    3.08                  3.08
Aelollo59                     2                    2.82                  5.63
Aenarap34                     1                    2.96                  2.96
Aeral43                       1                    4.40                  4.40
Aeral68                       1                    4.00                  4.00
Aeral97                       1                    4.80                  4.80
Aeralria27                    1                    4.09                  4.09
Aeralstical35                 1                    2.96                  2.96
Aeri84                        1                    1.61                  1.61
Aerillorin70                  1                    3.33                  3.33
Aerithllora36                 2                    4.32                  8.64
Aerithnucal56                 1                    4.40                  4.40
Aerithnuphos61                1                    4.91                  4.91
Aerithriaphos45               1                    1.56                  1.56
Aerithriaphos46               1                    2.18                  2.18
Aesri53                       1                    1.76                  1.76
Aesty53                       2                    1.96                  3.91
Aestysu37                     2                    2.69                  5.38
Aesur96                       1                    2.21                  2.21
Aesurstilis64                 1                    1.03                  1.03
...                         ...                     ...                   ...
Undosia27                     1                    3.77                  3.77
Undosian34                    2                    4.15                  8.30
Undotesta33                   1                    4.74                  4.74
Wailin72                      1                    2.73                  2.73
Yadacal26                     2                    3.27                  6.54
Yadaisuir65                   1                    4.09                  4.09
Yadam35                       1                    2.48                  2.48
Yadanu52                      1                    2.38                  2.38
Yadaphos40                    2                    2.68                  5.35
Yalae81                       2                    3.34                  6.69
Yalaeria91                    1                    1.06                  1.06
Yaliru88                      1                    3.03                  3.03
Yalo85                        1                    3.65                  3.65
Yalostiphos68                 1                    4.40                  4.40
Yana46                        1                    3.55                  3.55
Yarithllodeu72                1                    3.75                  3.75
Yarithrgue83                  1                    3.45                  3.45
Yarithrin84                   1                    4.14                  4.14
Yarithsurgue62                1                    4.94                  4.94
Yarolwen77                    1                    4.43                  4.43
Yasrisu92                     1                    3.44                  3.44
Yastyriaphos75                1                    4.75                  4.75
Yasur35                       1                    4.48                  4.48
Yasur85                       1                    1.10                  1.10
Yathecal72                    1                    3.46                  3.46
Yathecal82                    3                    2.07                  6.22
Yathedeu43                    2                    3.01                  6.02
Yoishirrala98                 1                    4.58                  4.58
Zhisrisu83                    2                    3.94                  7.89
Zontibe81                     3                    2.68                  8.03

[576 rows x 3 columns]

In [78]:
top_spenders_df.sort_values(by=['Total Purchase Value'], ascending=False, inplace=True)
top_spenders_df

               Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                   5                    3.79                 18.96
Idastidru52                 4                    3.86                 15.45
Chamjask73                  3                    4.61                 13.83
Iral74                      4                    3.40                 13.62
Iskadarya95                 3                    4.37                 13.10
Ilarin91                    3                    4.23                 12.70
Ialallo29                   3                    3.95                 11.84
Tyidaim51                   3                    3.94                 11.83
Lassilsala30                3                    3.84                 11.51
Chadolyla44                 3                    3.82                 11.46
Iri67                       3                    3.79                 11.37
Inguron55                   3                    3.70                 11.11
Siallylis44                 3                    3.46                 10.37
Saistyphos30                3                    3.44                 10.33
Phyali88                    3                    3.43                 10.30
Strithenu87                 3                    3.39                 10.18
Lisim78                     3                    3.34                 10.02
Haillyrgue51                3                    3.17                  9.50
Phistym51                   2                    4.75                  9.50
Lamil79                     2                    4.64                  9.29
Aina42                      3                    3.07                  9.22
Saesrideu94                 2                    4.59                  9.18
Arin32                      2                    4.54                  9.09
Rarallo90                   3                    3.02                  9.05
Baelollodeu94               2                    4.51                  9.03
Aelin32                     3                    2.99                  8.98
Lisopela58                  3                    2.95                  8.86
Saedaiphos46                3                    2.94                  8.83
Reunasu60                   2                    4.41                  8.82
Chanastnya43                3                    2.94                  8.82
...                       ...                     ...                   ...
Lirtim36                    1                    1.33                  1.33
Shidai42                    1                    1.33                  1.33
Philodil43                  1                    1.29                  1.29
Eyista89                    1                    1.29                  1.29
Mindilsa60                  1                    1.28                  1.28
Tyarithn67                  1                    1.14                  1.14
Aisur51                     1                    1.14                  1.14
Ilista82                    1                    1.14                  1.14
Jiskimsda56                 1                    1.14                  1.14
Aillyriadru65               1                    1.10                  1.10
Eryon48                     1                    1.10                  1.10
Iduelis31                   1                    1.10                  1.10
Yasur85                     1                    1.10                  1.10
Undjask33                   1                    1.10                  1.10
Lirtassa52                  1                    1.09                  1.09
Aelidru27                   1                    1.09                  1.09
Yalaeria91                  1                    1.06                  1.06
Aesurstilis64               1                    1.03                  1.03
Saida58                     1                    1.03                  1.03
Euthe35                     1                    1.03                  1.03
Hala31                      1                    1.02                  1.02
Qilalista41                 1                    1.02                  1.02
Frichjaskan98               1                    1.02                  1.02
Isurria36                   1                    1.02                  1.02
Eudanu84                    1                    1.02                  1.02
Ililsasya43                 1                    1.02                  1.02
Irilis75                    1                    1.02                  1.02
Aidai61                     1                    1.01                  1.01
Chanirra79                  1                    1.01                  1.01
Alo38                       1                    1.00                  1.00

[576 rows x 3 columns]

In [79]:
# Formatting the currency columns into $0.00 for ease of viewing
top_spenders_df['Average Purchase Price'] = top_spenders_df['Average Purchase Price'].map('${:,.2f}'.format)
top_spenders_df['Total Purchase Value'] = top_spenders_df['Total Purchase Value'].map('${:,.2f}'.format)

top_spenders_df.head()

             Purchase Count Average Purchase Price Total Purchase Value
SN
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [80]:
# Getting Purchase Count and Total Purchase Value
most_items_df = purchase_data.groupby(['Item ID', 'Item Name','Price'])['Price'].agg(['count','sum'])
most_items_df.columns = ['Purchase Count', 'Total Purchase Value']
most_items_df

,,,Purchase Count,Total Purchase Value
Item ID,Item Name,Price,,
0,Splinter,1.28,4,5.12
1,Crucifer,3.26,3,9.78
2,Verdict,2.48,6,14.88
3,Phantomlight,2.49,6,14.94
4,Bloodlord's Fetish,1.70,5,8.50
5,Putrid Fan,4.08,4,16.32
6,Rusty Skull,3.70,2,7.40
7,"Thorn, Satchel of Dark Souls",1.33,7,9.31
8,"Purgatory, Gem of Regret",3.93,3,11.79
9,"Thorn, Conqueror of the Corrupted",2.73,4,10.92
10,Sleepwalker,1.79,4,7.16
11,Brimstone,3.65,5,18.25
12,Dawne,1.02,6,6.12
13,Serenity,1.41,4,5.64
14,Possessed Core,2.61,2,5.22
15,Soul Infused Crystal,2.96,5,14.80
16,Restored Bauble,3.55,4,14.20
17,"Lazarus, Terror of the Earth",1.70,4,6.80
18,"Torchlight, Bond of Storms",4.65,2,9.30
19,"Pursuit, Cudgel of Necromancy",1.02,8,8.16
20,Netherbane,3.27,5,16.35
21,Souleater,1.10,5,5.50
22,Amnesia,2.18,6,13.08
23,Crucifer,1.99,1,1.99
24,Warped Fetish,3.81,5,19.05
25,Hero Cane,4.35,6,26.10
26,Unholy Wand,1.12,2,2.24
27,"Riddle, Tribute of Ended Dreams",3.30,1,3.30
28,"Flux, Destroyer of Due Diligence",1.06,2,2.12
29,"Chaos, Ender of the End",1.98,5,9.90
...,...,...,...,...
154,Feral Katana,4.40,4,17.60
155,War-Forged Gold Deflector,1.01,5,5.05
156,Soul-Forged Steel Shortsword,1.77,5,8.85
157,"Spada, Etcher of Hatred",4.80,4,19.20
158,"Darkheart, Butcher of the Champion",2.45,2,4.90
159,"Oathbreaker, Spellblade of Trials",3.08,7,21.56
160,Azurewrath,4.40,6,26.40
161,Devine,1.76,5,8.80
162,Abyssal Shard,2.67,5,13.35
163,Thunderfury Scimitar,3.45,5,17.25
164,Exiled Doomblade,1.63,7,11.41
165,Bone Crushing Silver Skewer,4.86,4,19.44
166,Thirsty Iron Reaver,3.07,3,9.21
167,"Malice, Legacy of the Queen",3.61,4,14.44
168,"Sun Strike, Jaws of Twisted Visions",1.48,2,2.96
169,"Interrogator, Blood Blade of the Queen",2.18,4,8.72
170,Shadowsteel,3.97,4,15.88
171,Scalpel,1.79,3,5.37
172,Blade of the Grave,3.14,4,12.56
173,Stormfury Longsword,4.93,2,9.86
174,Primitive Blade,3.47,4,13.88
175,Woeful Adamantite Claymore,4.48,3,13.44
176,Relentless Iron Skewer,2.84,2,5.68
177,"Winterthorn, Defender of Shifting Worlds",2.08,2,4.16
178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,12,50.76
179,"Wolf, Promise of the Moonwalker",4.48,6,26.88
180,Stormcaller,3.36,1,3.36
181,Reaper's Toll,1.66,5,8.30
182,Toothpick,4.03,3,12.09
183,Dragon's Greatsword,1.09,3,3.27

In [81]:
# Reformatting the index
most_items_df.reset_index(inplace=True)
most_items_df.set_index(['Item ID','Item Name'] ,inplace=True)
most_items_df

,,Price,Purchase Count,Total Purchase Value
Item ID,Item Name,,,
0,Splinter,1.28,4,5.12
1,Crucifer,3.26,3,9.78
2,Verdict,2.48,6,14.88
3,Phantomlight,2.49,6,14.94
4,Bloodlord's Fetish,1.70,5,8.50
5,Putrid Fan,4.08,4,16.32
6,Rusty Skull,3.70,2,7.40
7,"Thorn, Satchel of Dark Souls",1.33,7,9.31
8,"Purgatory, Gem of Regret",3.93,3,11.79
9,"Thorn, Conqueror of the Corrupted",2.73,4,10.92
10,Sleepwalker,1.79,4,7.16
11,Brimstone,3.65,5,18.25
12,Dawne,1.02,6,6.12
13,Serenity,1.41,4,5.64
14,Possessed Core,2.61,2,5.22
15,Soul Infused Crystal,2.96,5,14.80
16,Restored Bauble,3.55,4,14.20
17,"Lazarus, Terror of the Earth",1.70,4,6.80
18,"Torchlight, Bond of Storms",4.65,2,9.30
19,"Pursuit, Cudgel of Necromancy",1.02,8,8.16
20,Netherbane,3.27,5,16.35
21,Souleater,1.10,5,5.50
22,Amnesia,2.18,6,13.08
23,Crucifer,1.99,1,1.99
24,Warped Fetish,3.81,5,19.05
25,Hero Cane,4.35,6,26.10
26,Unholy Wand,1.12,2,2.24
27,"Riddle, Tribute of Ended Dreams",3.30,1,3.30
28,"Flux, Destroyer of Due Diligence",1.06,2,2.12
29,"Chaos, Ender of the End",1.98,5,9.90
...,...,...,...,...
154,Feral Katana,4.40,4,17.60
155,War-Forged Gold Deflector,1.01,5,5.05
156,Soul-Forged Steel Shortsword,1.77,5,8.85
157,"Spada, Etcher of Hatred",4.80,4,19.20
158,"Darkheart, Butcher of the Champion",2.45,2,4.90
159,"Oathbreaker, Spellblade of Trials",3.08,7,21.56
160,Azurewrath,4.40,6,26.40
161,Devine,1.76,5,8.80
162,Abyssal Shard,2.67,5,13.35
163,Thunderfury Scimitar,3.45,5,17.25
164,Exiled Doomblade,1.63,7,11.41
165,Bone Crushing Silver Skewer,4.86,4,19.44
166,Thirsty Iron Reaver,3.07,3,9.21
167,"Malice, Legacy of the Queen",3.61,4,14.44
168,"Sun Strike, Jaws of Twisted Visions",1.48,2,2.96
169,"Interrogator, Blood Blade of the Queen",2.18,4,8.72
170,Shadowsteel,3.97,4,15.88
171,Scalpel,1.79,3,5.37
172,Blade of the Grave,3.14,4,12.56
173,Stormfury Longsword,4.93,2,9.86
174,Primitive Blade,3.47,4,13.88
175,Woeful Adamantite Claymore,4.48,3,13.44
176,Relentless Iron Skewer,2.84,2,5.68
177,"Winterthorn, Defender of Shifting Worlds",2.08,2,4.16
178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,12,50.76
179,"Wolf, Promise of the Moonwalker",4.48,6,26.88
180,Stormcaller,3.36,1,3.36
181,Reaper's Toll,1.66,5,8.30
182,Toothpick,4.03,3,12.09
183,Dragon's Greatsword,1.09,3,3.27

In [82]:
# Renaming Dataframe columns
most_items_df = most_items_df[['Purchase Count', 'Price', 'Total Purchase Value']]
most_items_df

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
0,Splinter,4,1.28,5.12
1,Crucifer,3,3.26,9.78
2,Verdict,6,2.48,14.88
3,Phantomlight,6,2.49,14.94
4,Bloodlord's Fetish,5,1.70,8.50
5,Putrid Fan,4,4.08,16.32
6,Rusty Skull,2,3.70,7.40
7,"Thorn, Satchel of Dark Souls",7,1.33,9.31
8,"Purgatory, Gem of Regret",3,3.93,11.79
9,"Thorn, Conqueror of the Corrupted",4,2.73,10.92
10,Sleepwalker,4,1.79,7.16
11,Brimstone,5,3.65,18.25
12,Dawne,6,1.02,6.12
13,Serenity,4,1.41,5.64
14,Possessed Core,2,2.61,5.22
15,Soul Infused Crystal,5,2.96,14.80
16,Restored Bauble,4,3.55,14.20
17,"Lazarus, Terror of the Earth",4,1.70,6.80
18,"Torchlight, Bond of Storms",2,4.65,9.30
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16
20,Netherbane,5,3.27,16.35
21,Souleater,5,1.10,5.50
22,Amnesia,6,2.18,13.08
23,Crucifer,1,1.99,1.99
24,Warped Fetish,5,3.81,19.05
25,Hero Cane,6,4.35,26.10
26,Unholy Wand,2,1.12,2.24
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
29,"Chaos, Ender of the End",5,1.98,9.90
...,...,...,...,...
154,Feral Katana,4,4.40,17.60
155,War-Forged Gold Deflector,5,1.01,5.05
156,Soul-Forged Steel Shortsword,5,1.77,8.85
157,"Spada, Etcher of Hatred",4,4.80,19.20
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
160,Azurewrath,6,4.40,26.40
161,Devine,5,1.76,8.80
162,Abyssal Shard,5,2.67,13.35
163,Thunderfury Scimitar,5,3.45,17.25
164,Exiled Doomblade,7,1.63,11.41
165,Bone Crushing Silver Skewer,4,4.86,19.44
166,Thirsty Iron Reaver,3,3.07,9.21
167,"Malice, Legacy of the Queen",4,3.61,14.44
168,"Sun Strike, Jaws of Twisted Visions",2,1.48,2.96
169,"Interrogator, Blood Blade of the Queen",4,2.18,8.72
170,Shadowsteel,4,3.97,15.88
171,Scalpel,3,1.79,5.37
172,Blade of the Grave,4,3.14,12.56
173,Stormfury Longsword,2,4.93,9.86
174,Primitive Blade,4,3.47,13.88
175,Woeful Adamantite Claymore,3,4.48,13.44
176,Relentless Iron Skewer,2,2.84,5.68
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
179,"Wolf, Promise of the Moonwalker",6,4.48,26.88
180,Stormcaller,1,3.36,3.36
181,Reaper's Toll,5,1.66,8.30
182,Toothpick,3,4.03,12.09
183,Dragon's Greatsword,3,1.09,3.27

In [83]:
# Sorting by most popular (Highest Purchase Count)
most_popular_items_df = most_items_df.sort_values(by='Purchase Count', ascending=False)
most_popular_items_df

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
145,Fiery Glass Crusader,9,4.58,41.22
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
82,Nirvana,9,4.90,44.10
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16
103,Singed Scalpel,8,4.35,34.80
75,Brutality Ivory Warmace,8,2.42,19.36
72,Winter's Bite,8,3.77,30.16
60,Wolf,8,3.54,28.32
59,"Lightning, Etcher of the King",8,4.23,33.84
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
34,Retribution Axe,8,2.22,17.76
92,Final Critic,8,4.88,39.04
53,Vengeance Cleaver,7,2.05,14.35
110,Suspension,7,1.44,10.08
7,"Thorn, Satchel of Dark Souls",7,1.33,9.31
71,Demise,7,1.61,11.27
117,"Heartstriker, Legacy of the Light",7,1.79,12.53
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
85,Malificent Bag,7,1.75,12.25
164,Exiled Doomblade,7,1.63,11.41
141,Persuasion,7,3.19,22.33
78,"Glimmer, Ender of the Moon",7,4.40,30.80
102,Avenger,6,3.44,20.64
129,"Fate, Vengeance of Eternal Justice",6,1.54,9.24
93,Apocalyptic Battlescythe,6,1.97,11.82
54,Eternal Cleaver,6,2.50,15.00
3,Phantomlight,6,2.49,14.94
2,Verdict,6,2.48,14.88
40,Second Chance,6,2.52,15.12
...,...,...,...,...
81,Dreamkiss,2,3.61,7.22
6,Rusty Skull,2,3.70,7.40
18,"Torchlight, Bond of Storms",2,4.65,9.30
26,Unholy Wand,2,1.12,2.24
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
30,Stormcaller,2,2.21,4.42
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
69,"Frenzy, Defender of the Harvest",2,1.98,3.96
132,Persuasion,2,3.33,6.66
63,Stormfury Mace,2,4.99,9.98
56,Foul Titanium Battle Axe,2,2.92,5.84
127,"Heartseeker, Reaver of Souls",2,3.92,7.84
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
125,Whistling Mithril Warblade,2,1.00,2.00
43,Foul Edge,2,3.54,7.08
115,Spectral Diamond Doomblade,2,2.04,4.08
33,Curved Axe,2,1.16,2.32
31,Trickster,2,1.55,3.10
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
42,The Decapitator,1,1.75,1.75
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
126,Exiled Mithril Longsword,1,2.00,2.00
51,Endbringer,1,4.66,4.66
90,Betrayer,1,2.94,2.94
104,Gladiator's Glaive,1,1.93,1.93
23,Crucifer,1,1.99,1.99
180,Stormcaller,1,3.36,3.36
91,Celeste,1,4.17,4.17
134,Undead Crusader,1,4.50,4.50

In [84]:
# Formatting the currency columns into $0.00 for ease of viewing
most_popular_items_df['Price'] = most_popular_items_df['Price'].map('${:,.2f}'.format)
most_popular_items_df['Total Purchase Value'] = most_popular_items_df['Total Purchase Value'].map('${:,.2f}'.format)

most_popular_items_df.head()

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
145,Fiery Glass Crusader,9,$4.58,$41.22
108,"Extraction, Quickblade Of Trembling Hands",9,$3.53,$31.77
82,Nirvana,9,$4.90,$44.10
19,"Pursuit, Cudgel of Necromancy",8,$1.02,$8.16

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [85]:
# Sorting by most profitable (Total Purchase Value)
most_profitable_items_df = most_items_df.sort_values(by='Total Purchase Value', ascending=False)
most_profitable_items_df

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80
59,"Lightning, Etcher of the King",8,4.23,33.84
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
78,"Glimmer, Ender of the Moon",7,4.40,30.80
72,Winter's Bite,8,3.77,30.16
60,Wolf,8,3.54,28.32
179,"Wolf, Promise of the Moonwalker",6,4.48,26.88
160,Azurewrath,6,4.40,26.40
25,Hero Cane,6,4.35,26.10
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
139,"Mercy, Katana of Dismay",5,4.94,24.70
128,"Blazeguard, Reach of Eternity",5,4.91,24.55
138,"Peacekeeper, Wit of Dark Magic",5,4.74,23.70
141,Persuasion,7,3.19,22.33
87,"Deluge, Edge of the West",5,4.43,22.15
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
136,Ghastly Adamantite Protector,6,3.58,21.48
65,Conqueror Adamantite Mace,5,4.24,21.20
101,Final Critic,5,4.19,20.95
102,Avenger,6,3.44,20.64
133,Faith's Scimitar,5,4.09,20.45
39,"Betrayal, Whisper of Grieving Widows",5,3.94,19.70
111,Misery's End,4,4.89,19.56
165,Bone Crushing Silver Skewer,4,4.86,19.44
75,Brutality Ivory Warmace,8,2.42,19.36
52,Hatred,4,4.84,19.36
...,...,...,...,...
124,Venom Claymore,4,1.29,5.16
0,Splinter,4,1.28,5.12
155,War-Forged Gold Deflector,5,1.01,5.05
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
51,Endbringer,1,4.66,4.66
134,Undead Crusader,1,4.50,4.50
30,Stormcaller,2,2.21,4.42
135,Warped Diamond Crusader,3,1.40,4.20
91,Celeste,1,4.17,4.17
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
70,Hope's End,4,1.03,4.12
115,Spectral Diamond Doomblade,2,2.04,4.08
69,"Frenzy, Defender of the Harvest",2,1.98,3.96
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
180,Stormcaller,1,3.36,3.36
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
183,Dragon's Greatsword,3,1.09,3.27
31,Trickster,2,1.55,3.10
168,"Sun Strike, Jaws of Twisted Visions",2,1.48,2.96
90,Betrayer,1,2.94,2.94
33,Curved Axe,2,1.16,2.32
26,Unholy Wand,2,1.12,2.24
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
125,Whistling Mithril Warblade,2,1.00,2.00
126,Exiled Mithril Longsword,1,2.00,2.00
23,Crucifer,1,1.99,1.99
104,Gladiator's Glaive,1,1.93,1.93
42,The Decapitator,1,1.75,1.75

In [86]:
# Formatting the currency columns into $0.00 for ease of viewing
most_profitable_items_df['Price'] = most_profitable_items_df['Price'].map('${:,.2f}'.format)
most_profitable_items_df['Total Purchase Value'] = most_profitable_items_df['Total Purchase Value'].map('${:,.2f}'.format)

most_profitable_items_df.head()

,,Purchase Count,Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
82,Nirvana,9,$4.90,$44.10
145,Fiery Glass Crusader,9,$4.58,$41.22
92,Final Critic,8,$4.88,$39.04
103,Singed Scalpel,8,$4.35,$34.80